config/routes.rb
Hanzi::Application.routes.draw do

  resources :groups

  root :to => 'hanzi_chars#index'

  resources :hanzi_chars
  resources :flashcard_sets do
    member do
      get :show_result
      get :record_result
    end
  end
  resource :csv, :only => :create

end

app/models/flashcard_set.rb
# == Schema Information
#
# Table name: flashcard_sets
#
#  id               :integer          not null, primary key
#  num_cards        :integer
#  num_tested       :integer
#  groups           :string(255)
#  serialized_cards :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#



class FlashcardSet < ActiveRecord::Base
  attr_accessible :cards, :num_cards, :num_tested

  attr_accessor :cards

  serialize :groups, Array

  has_and_belongs_to_many :groups

  
  before_save :serialize_cards
  after_find  :deserialize_cards


  def serialize_cards
    serialized_cards_array = @cards.map(&:serialize)
    self.serialized_cards = serialized_cards_array.join(';')
  end


  def deserialize_cards
    serialized_cards_array = self.serialized_cards.split(';')
    @cards = serialized_cards_array.map{ |card| Flashcard.deserialize(card) }
  end


  def self.new_from_ids(hanzi_char_ids)
    set = self.new
    set.num_tested = 0
    set.generate_cards_from_ids(hanzi_char_ids)
    set
  end

 

  def generate_cards_from_ids(hanzi_char_ids)
    @cards = Array.new
    pinyin_offset = hanzi_char_ids.size
    english_offset = hanzi_char_ids.size * 2
    card_sides_set = [ [:chinese, :pinyin, :english], [:pinyin, :english, :chinese], [:english, :chinese, :pinyin] ]
    hanzi_char_ids.each_with_index do |hanzi_char_id, index|
      mod = index % 3
      card_sides = card_sides_set[mod]
      @cards << Flashcard.new(hanzi_char_id, card_sides[0], index)
      @cards << Flashcard.new(hanzi_char_id, card_sides[1], index + pinyin_offset)
      @cards << Flashcard.new(hanzi_char_id, card_sides[2], index + english_offset)
    end
    self.num_cards = @cards.size
    self.cards.sort!  
    self
  end


 



  def next_card
    self.cards[num_tested]
  end


  def record_result(card, result)
    raise ArgumentError unless [:true, :false].include?(result)
    card.status = result
    @cards[card.sequence_id] = card
    self.num_tested +=1 
    self.save!
  end


  # This method reviews the result, and updates the boxes accordingly.
  def update_boxes
    raise "Update boxes called before all cards in set have been tested" unless self.num_cards == self.num_tested
    correct_ids = []
    wrong_ids = []
    @cards.each do |card|
      card.answered_correctly? ? correct_ids << card.hanzi_char_id : wrong_ids << card.hanzi_char_id
    end
    
    # a card may have been answered correctly on one side, but wrong on the other, so we don't count it as correct
    card_ids_to_promote = correct_ids - wrong_ids
    HanziChar.promote(card_ids_to_promote) unless card_ids_to_promote.empty?
    HanziChar.demote(wrong_ids) unless wrong_ids.empty?
  end





  private

  def sequence_cards
    @cards.each_with_index do |card, index|
      card.sequence_id = index
    end
  end

  
  # returns the wrap-round index
  def wrap_around(num_cards, index)
    if index > num_cards - 1
      index = index - num_cards
    end
    index
  end



end

app/models/hanzi_char.rb
# encoding: UTF-8
# == Schema Information
#
# Table name: hanzi_chars
#
#  id              :integer          not null, primary key
#  character       :string(255)
#  pinyin          :string(255)
#  meaning         :text
#  strokes         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  mnemonic        :text
#  box_id          :integer          default(1)
#  sortable_pinyin :string(255)
#


class HanziChar < ActiveRecord::Base


  attr_accessible :character, :meaning, :pinyin, :strokes, :mnemonic, :group_ids, :box_id, :tone_hint

  has_many :groups, :through => :grouped_hanzi

  has_many :grouped_hanzi

  belongs_to :box, :counter_cache => true

  before_save :transform_pinyin_and_mnemonic

  validates :character, :uniqueness => true
  validates :character, :presence => true
  validates :pinyin,    :presence=> true



  # Returns all records, optionally constrained by a group id and / or starting from a certain pinyin character 
  # ordered by sortable_pinyin
  # @param [String] : pinyin_start_character : only return records with sortable pinyin equal to or greater than this character
  # @param [Fixnum] : group_id : only return records in this group, or all groups if nil
  #
  def self.all_by_pinyin(pinyin_start_char = nil, group_id = nil)
    pinyin_start_char = 'a' if pinyin_start_char.nil?
    if group_id.nil?
      recs = self.where('sortable_pinyin > ?', pinyin_start_char).includes(:groups)
    else
      recs = self.joins(:groups).where('sortable_pinyin > ?', pinyin_start_char).includes(:groups).where('groups.id' => group_id)
    end
    recs = recs.order(:sortable_pinyin)
  end



  # returns a hash of record ids, keyed by box number
  def self.ids_by_box_id(group_ids)
    hcs_hashed_by_box_id = HanziChar.select('id, box_id').group_by(&:box_id)
    ids_hashed_by_box_id = {}
    hcs_hashed_by_box_id.each { |box_id, hc_array| ids_hashed_by_box_id[box_id] = hc_array.map(&:id) }
    ids_hashed_by_box_id
  end





  def self.to_csv
    # filename = "#{ENV['HOME']}/hanzi_chars.#{Time.now.strftime('%Y%m%d_%H%M%S')}.csv"
    CSV.generate do |csv|
      csv << ["English","Traditional Chinese","Simplified Chinese","Pinyin","Box","Quiz English","Quiz Chinese","Quiz Pinyin","GroupName"]
      HanziChar.all.each do |hc|
        csv << [hc.meaning, '', hc.character, hc.pinyin, hc.box_id, 1,1,1,'']
      end
    end
    
  end



  # returns an array of ids of all the HanziChar ids in the specified_group_ids
  def self.ids_for_groups(group_ids)
    GroupedHanzi.select(:hanzi_char_id).where('group_id in (?)', group_ids).map(&:hanzi_char_id).uniq
  end




  # Returns the number of cards per box - only counting HanziChars in the specified group_ids
  # @param [Array] group_ids - Only count cards in the groups in this array.  Default is nil, meaning all groups.
  # returns Hash  keyed by box, with the value being the number of cards per box
  #
  def self.num_per_box(group_ids = nil)
    if group_ids.nil?
      hcids = HanziChar.all.map(&:id)
    else
      hcids = HanziChar.ids_for_groups(group_ids)
    end
    id_hash = HanziChar.select([:id, :box_id]).where('id in (?)', hcids).group_by(&:box_id)
    record_count_hash = {}
    id_hash.each { |key, value_array| record_count_hash[key] = value_array.size }
    record_count_hash
  end






  def self.promote(ids)
    recs = HanziChar.find(ids)
    recs.each do |rec|
      if rec.box.id != 5
        rec.box = Box.find(rec.box_id + 1)
        rec.save
      end
    end
  end



  def self.demote(ids)
    recs = HanziChar.find(ids)
    recs.each do |rec|
      if rec.box_id != 1
        rec.box Box.find(rec.box_id - 1)
        rec.save!
      end
    end
  end




  def transform_pinyin_and_mnemonic
    self.pinyin = Pinyin.new(self.pinyin).to_s
    self.sortable_pinyin = SortablePinyinCreator.new(self.pinyin).create
    self.mnemonic = EmbeddedPinyin.new(self.mnemonic).to_s unless self.mnemonic.nil?
  end


  def to_s
    self.character + ' ' + self.pinyin
  end



  def group_names
    groups.map(&:name).join(", ")
  end


  # This enables groups to be specified on the  incoming params as an array of ids
  def group_ids=(group_ids)
    group_ids.delete("")
    groups = Group.find(group_ids)
    self.groups = groups
  end


  # decorator_methods

  def decorate_mnemonic
    self.mnemonic.blank? ? "None" : self.mnemonic
  end


  def decorate_tone_hint
    self.tone_hint.blank? ? "None" : self.tone_hint
  end


  def decorate_mnemonic_present?
    self.mnemonic.blank? ? "N" : "Y"
  end


  def decorate_tone_hint_present?
    self.tone_hint.blank? ? "N" : "Y"
  end






end

app/controllers/hanzi_chars_controller.rb
class HanziCharsController < ApplicationController

  before_filter :check_for_cancel, :only => [:create, :update]


  def index
    pinyin_start_char = params[:pinyin]
    group_id = extract_group_id(params)
    @hanzis = HanziChar.all_by_pinyin(pinyin_start_char, group_id).page(params[:page]).per(20)
    @groups_array = Group.all_by_name.map { |group| [group.name, group.id] }
    @groups_array.unshift ['All Groups', nil] 
  end

  def show
    @hanzi = HanziChar.find(params[:id])
  end

  def new
    @hanzi = HanziChar.new
    @groups = Group.all_by_name
  end

  def create
    begin
      if @hanzi = HanziChar.create!(params[:hanzi_char])
        flash[:notice] = "Character created: #{@hanzi}"
        redirect_to hanzi_chars_path
      else
        flash[:error] = 'Unable to create character'
        redirect_to new_hanzi_char_path
      end
    rescue => err
      flash[:error] = err.message
      redirect_to new_hanzi_char_path
    end
  end


  def edit
    @hanzi = HanziChar.find(params[:id])
    @groups = Group.all
  end

  def update
    @hanzi = HanziChar.find(params[:id])
    @hanzi.update_attributes(params[:hanzi_char])
    flash[:notice] = "Character Updated: #{@hanzi}"
    redirect_to hanzi_chars_path
  end

  def destroy
  end






  private


  def extract_group_id(params)
    return nil unless params.has_key?(:group)
    return nil if params[:group][:group_id].blank?
    return params[:group][:group_id].to_i
  end


  def check_for_cancel
    if params[:commit] == "Cancel"
      redirect_to hanzi_chars_path
    end
  end

end

app/views/hanzi_chars/_hanzi_char_edit_form.haml
= simple_form_for @hanzi do |f| 
  = f.input :character, :autofocus => true
  = f.input :pinyin
  = f.input :meaning, input_html: { class: 'input-xxlarge', rows: '4' }
  = f.input :mnemonic, input_html: { class: 'input-xxlarge', rows: '4'  }
  = f.input :tone_hint, input_html: {class: 'input-xxlarge', rows: '2' }
  = f.input :strokes 
  = f.collection_check_boxes :group_ids, Group.all_by_name, :id, :name, {:item_wrapper_class => 'checkbox_container'}
  %p
  = f.submit 'Update', :class => 'btn btn-danger'
  = f.submit "Cancel", :class => 'btn btn-warning'



 

app/views/hanzi_chars/_index_by_initials.haml
-%w{ a b c d e f g h i j k l m n o p q r s t u w x y z }.each do |letter|
  =link_to("#{letter}&nbsp;&nbsp;".html_safe, hanzi_chars_path(:pinyin => letter))

app/views/hanzi_chars/create.html.haml
%h1 HanziCharsController#create
%p Find me in app/views/hanzi_chars_controller/create.html.haml

app/views/hanzi_chars/destroy.html.haml
%h1 HanziCharsController#destroy
%p Find me in app/views/hanzi_chars_controller/destroy.html.haml

app/views/hanzi_chars/edit.html.haml
%h1 Edit Hanzi character

=render :partial => 'hanzi_char_edit_form'

app/views/hanzi_chars/index.html.haml
.container-fluid
  .row-fluid
    %h1 Hanzi Character List

  .row-fluid
    .span6
      =form_tag csv_path, :method => :post do
        %a.btn.btn-primary.btn-small{:href => new_hanzi_char_path }
          New Hanzi
        %a.btn.btn-primary.btn-small{:href => new_flashcard_set_path }
          Create Flashcard Set
        =submit_tag "Generate CSV", :class => 'btn btn-primary btn-small'
    .span4.offset2{:align => "right"}
      =form_tag hanzi_chars_path, :method => :get, :class => 'form-inline' do
        =select("group", "group_id", @groups_array)
        =submit_tag "Filter", :class => 'btn btn-primary btn-small'

  .row-fluid
    .span12.text-right
      =render :partial => 'index_by_initials'

  


  .row-fluid
    %table.table.table-condensed.table-bordered
      %tr
        %th Hanzi
        %th Pinyin
        %th Meaning
        %th Groups
        %th Box
        %th Mnemonic
        %th Tone Hint
       

      - @hanzis.each do |hanzi|
        %tr
          %td.hanzi= link_to(hanzi.character, hanzi_char_path(hanzi))
          %td= hanzi.pinyin
          %td= hanzi.meaning
          %td= hanzi.group_names
          %td= hanzi.box_id
          %td= hanzi.decorate_mnemonic_present?
          %td= hanzi.decorate_tone_hint_present?
          

  .row
    = paginate(@hanzis)

app/views/hanzi_chars/new.html.haml
%h1 New Hanzi Character


=render :partial => 'hanzi_char_edit_form'

app/views/hanzi_chars/show.html.haml
%h1.hanzi.supersized= @hanzi.character
%h3= @hanzi.pinyin
%p

%br

%h5 Meaning:
%p= @hanzi.meaning

%h5 Mnemonic:
%p= @hanzi.decorate_mnemonic

%h5 Tone Hint:
%p= @hanzi.decorate_tone_hint


%br



= link_to 'Index Page', hanzi_chars_path, :class => 'btn btn-primary'
&nbsp;
= link_to 'Edit', edit_hanzi_char_path(@hanzi), :class => 'btn btn-danger'

app/views/hanzi_chars/update.html.haml
%h1 HanziCharsController#update
%p Find me in app/views/hanzi_chars_controller/update.html.haml