config/routes.rb
Hanzi::Application.routes.draw do

  resources :groups

  root :to => 'hanzi_chars#index'

  resources :hanzi_chars
  resources :flashcard_sets do
    member do
      get :show_result
      get :record_result
    end
  end
  resource :csv, :only => :create

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Group < ActiveRecord::Base
  attr_accessible :name

  has_many :hanzi_chars, :through => :grouped_hanzi

  has_many :grouped_hanzi

  has_and_belongs_to_many :flashcard_sets

  scope :all_by_name, order('name')

  scope :named_default, where(:name => 'Default')

  def self.all_ids
    self.all.map(&:id)
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= simple_form_for(@group) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h1 Listing groups

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @groups.each do |group|
    %tr
      %td= group.name
      %td= link_to 'Show', group
      %td= link_to 'Edit', edit_group_path(group)
      %td= link_to 'Destroy', group, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path