config/routes.rb
Hanzi::Application.routes.draw do

  resources :groups

  root :to => 'hanzi_chars#index'

  resources :hanzi_chars
  resources :flashcard_sets do
    member do
      get :show_result
      get :record_result
    end
  end
  resource :csv, :only => :create

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String) || msg.is_a?(Array)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      - if msg.is_a?(String)
        = content_tag :div, msg, :id => "flash_#{name}"
      - else
        %ul
          - msg.each do |item|
            %li= item
          

app/views/layouts/_navigation.html.haml
/ = link_to "Hanzi Characters", root_path, :class => 'brand'
%ul.nav
  %li 
    =link_to 'Home', hanzi_chars_path
  %li 
    =link_to 'Groups', groups_path
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Hanzi"
      %meta{:content => content_for?(:description) ? yield(:description) : "Hanzi", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              %br
              = yield
          %footer
            %p.muted
              Revision: 
              = @revision
      / ! end of .container
    / ! end of #main